### ISSUE TITLE
Remove jquery

### ISSUE THREAD

**Issue by waywardmonkeys** [endoli/endoli.com#2]
I'd rather not load jquery anywhere if we don't have to. The functionality that it is used for seems minor enough that we don't need it. (And that functionality isn't even getting used at the moment...)

**Comment by synthmeat** [comment]
Fixed by 2a425c0d8bd65e19d2dbc0a3bac275270e9968ad

**Comment by waywardmonkeys** [comment]
Doesn't https://github.com/endoli/endoli.com/blob/325dd4de3f8dbadb7337557dd367fd89b5dc659f/scripts/front/page.js need to be updated for this?

**Comment by synthmeat** [comment]
It does. Fixed by 8a9e46d0c5663956038ee1ba5e76829cb85691c1
